---
  - hosts: localhost
    gather_facts: false
    connection: local
    
    tasks:
      - name: Create resource group
        azure_rm_resourcegroup:
          name: ansibleactions
          location: eastus
